{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secrets
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | default "amRiYzpwb3N0Z3Jlc3FsOi8vdXNlcjpwYXNzQHBvc3RncmVzLWF1dGg6NTQzMi9hdXRoX2Ri" | b64enc }}
  database-username: {{ .Values.secrets.databaseUsername | default "dXNlcg==" | b64enc }}
  database-password: {{ .Values.secrets.databasePassword | default "cGFzcw==" | b64enc }}
  kafka-brokers: {{ .Values.secrets.kafkaBrokers | default "a2Fma2E6OTA5Mg==" | b64enc }}
{{- end }}