{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "subscription-service.fullname" . }}-secrets
  labels:
    {{- include "subscription-service.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | default "cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bwb3N0Z3Jlcy1zdWJzY3JpcHRpb246NTQzMi9zdWJzY3JpcHRpb25fZGI=" | b64enc }}
  database-username: {{ .Values.secrets.databaseUsername | default "dXNlcg==" | b64enc }}
  database-password: {{ .Values.secrets.databasePassword | default "cGFzcw==" | b64enc }}
  jwt-public-key-url: {{ .Values.secrets.jwtPublicKeyUrl | default "aHR0cDovL2F1dGgtc2VydmljZTo4MDgxL2FwaS92MS9hdXRoL3B1YmxpYy1rZXk=" | b64enc }}
  kafka-brokers: {{ .Values.secrets.kafkaBrokers | default "a2Fma2E6OTA5Mg==" | b64enc }}
{{- end }}