{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog-service.fullname" . }}-secrets
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
type: Opaque
data:
  mongo-uri: {{ .Values.secrets.mongoUri | default "bW9uZ29kYjovL21vbmdvOjI3MDE3" | b64enc }}
  redis-addr: {{ .Values.secrets.redisAddr | default "cmVkaXM6NjM3OQ==" | b64enc }}
  kafka-brokers: {{ .Values.secrets.kafkaBrokers | default "a2Fma2E6OTA5Mg==" | b64enc }}
  jwt-public-key-url: {{ .Values.secrets.jwtPublicKeyUrl | default "aHR0cDovL2F1dGgtc2VydmljZTo4MDgxL2FwaS92MS9hdXRoL3B1YmxpYy1rZXk=" | b64enc }}
{{- end }}