apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: food-subscription
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subscription-service
  namespace: food-subscription
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-service
  namespace: food-subscription